In [11]:
import pandas as pd
mapping = {'Novice 1': 1, 'Novice 2': 1, 'A Level 1': 2, 'A Level 2': 3, 'B Level 1': 4, 'B Level 2': 5, 'C Level 1': 6}
def replace(x):
    return mapping[x]

In [12]:
tocfl = pd.read_csv('./data/TOCFL_en.csv', index_col=0)
tocfl['level'] = tocfl['level'].apply(replace)
tocfl = tocfl.drop(['level 2'], axis=1)
tocfl = tocfl.reset_index()
tocfl['index'] = tocfl['index'] + 1
tocfl['number'] = tocfl['number'].astype(int)
tocfl['char 2'] = (tocfl['character']
                   .str.replace(r'\(.*\)', '', regex=True)
                   .str.replace('（.*）', '', regex=True)
                   .str.strip())
tocfl['char 3'] = (tocfl['char 2']
                   .str.replace(r'\/.*', '', regex=True)
                   .str.strip())
tocfl['zhuyin'] = tocfl['zhuyin'].str.replace('', '')

In [13]:
tocfl.loc[894, 'char 3'] = '手錶'
# tocfl.loc[1432]
# tocfl.loc[1444]
tocfl.loc[1690, 'char 3'] = '裡面'
# tocfl.loc[2024]
# tocfl.loc[2460]
tocfl.loc[2683, 'char 3'] = '潮濕'
tocfl.loc[2887, 'char 3'] = '電視臺'
tocfl.loc[2888, 'char 3'] = '電臺'
tocfl.loc[3009, 'char 3'] = '分佈'
tocfl.loc[3173, 'char 3'] = '規劃'
tocfl.loc[3174, 'char 3'] = '規劃'
tocfl.loc[3781, 'char 3'] = '鈕釦'
tocfl.loc[4215, 'char 3'] = '算賬'
tocfl.loc[4401, 'char 3'] = '舞臺'
tocfl.loc[4415, 'char 3'] = '吸煙'
tocfl.loc[5128, 'char 3'] = '不至於'
tocfl.loc[5452, 'char 3'] = '獨佔'
# tocfl.loc[5723]
tocfl.loc[5995, 'char 3'] = '艱巨'
tocfl.loc[6670, 'char 3'] = '橋梁'
tocfl.loc[6797, 'char 3'] = '散佈'
tocfl.loc[7050, 'char 3'] = '臺階'
tocfl.loc[7236, 'char 3'] = '污染'
tocfl.loc[7286, 'char 3'] = '鮮豔'
tocfl.loc[7632, 'char 3'] = '月臺'
tocfl.loc[7669, 'char 3'] = '佔據'
tocfl.loc[7670, 'char 3'] = '佔領'
tocfl.loc[7830, 'char 3'] = '註定'
tocfl.loc[7854, 'char 3'] = '轉賬'
tocfl.loc[7926, 'char 3'] = '嘴唇'

In [14]:
cedict = pd.read_csv('./data/cedict_2.csv')
cedict['dict_number'] = cedict.index

In [15]:
merged = pd.merge(left=tocfl, right=cedict, how='left', left_on='char 3', right_on='traditional')
merged['topic'] = merged['topic'].fillna('')
merged['part of speech'] = merged['part of speech'].fillna('')
merged.loc[1587, ['traditional', 'simplified', 'pinyin_y', 'english']] = ['還要', '还要', 'hai2 yao4', 'to an even greater degree or in an even greater amount']
merged.loc[1602, ['traditional', 'simplified', 'pinyin_y', 'english']] = ['好了', '好了', 'hao3 le5', 'alright; done!']
merged.loc[2248, ['traditional', 'simplified', 'pinyin_y', 'english']] = ['說起來', '说起來', 'shuo1 qi5 lai5', 'speaking of']
merged.loc[2718, ['traditional', 'simplified', 'pinyin_y', 'english']] = ['走走', '走走', 'zou3 zou5', 'take a walk']
merged.loc[6230, ['traditional', 'simplified', 'pinyin_y', 'english']] = ['古跡', '古迹', 'gu3 ji1', 'historical site']
merged.loc[4079, 'pinyin_x'] = 'mì'
merged.loc[5201, ['traditional', 'pinyin_y']] = ['占有' , 'zhan4you3']
merged.loc[6350, 'pinyin_y'] = 'heng5'
merged.loc[6582, 'pinyin_y'] = 'jie2 shi5'
merged.loc[6823, 'pinyin_x'] = 'li'
merged.loc[7364, 'pinyin_x'] = 'shā'
merged = merged.loc[:, ['index', 'traditional', 'simplified', 'zhuyin', 'pinyin_x', 'pinyin_y', 'english', 'level', 'number', 'part of speech', 'topic']]
merged.shape

(8541, 11)

In [16]:
merged = merged.drop([48, 49, 50, 53, 55, 70, 78, 85, 88, 98], axis=0)
merged = merged.drop([105, 109, 111, 113, 115, 116, 117, 128, 129, 131, 134, 142, 143, 146, 147, 149,
                      152, 155, 159, 168, 170, 171, 176, 177, 179, 180, 184, 199], axis=0)
merged = merged.drop([204, 240, 243, 283, 286, 295], axis=0)
merged = merged.drop([301, 302, 303, 308, 319, 335, 340, 348, 349, 351, 353, 356,
                      360, 365, 370, 372, 378, 379, 380, 381, 384, 385, 387, 388], axis=0)
merged = merged.drop([412, 424, 468, 471, 485], axis=0)
merged = merged.drop([527, 554, 558, 574, 578], axis=0)
merged = merged.drop([611, 625, 628, 639, 656, 658, 659, 672, 679], axis=0)
merged = merged.drop([714, 718, 721, 768, 771, 791, 794, 798], axis=0)
merged = merged.drop([807, 825, 833, 870, 877, 887, 889, 892, 893, 894, 895], axis=0)
merged = merged.drop([905, 916, 927, 931, 942, 944, 948, 969, 972], axis=0)
merged = merged.drop([1003, 1021, 1063, 1074, 1089, 1090], axis=0)
merged = merged.drop([1101, 1117, 1125, 1137, 1179, 1180], axis=0)
merged = merged.drop([1244, 1249, 1255, 1273, 1281], axis=0)
merged = merged.drop([1319, 1324, 1325, 1341, 1346, 1348, 1353, 1365, 1369, 1372, 1371, 1378, 1377, 1386], axis=0)
merged = merged.drop([1412, 1436, 1437, 1467, 1469], axis=0)
merged = merged.drop([1510, 1520, 1523, 1582, 1594, 1596, 1599], axis=0)
merged = merged.drop([1605, 1606, 1607, 1608, 1610, 1614, 1618, 1636, 1644, 1686, 1688], axis=0)
merged = merged.drop([1702, 1718, 1725, 1738, 1740, 1743, 1764, 1780], axis=0)
merged = merged.drop([1807, 1809, 1816, 1827, 1831, 1845, 1854, 1859, 1861, 1870, 1893, 1895], axis=0)
merged = merged.drop([1906, 1907, 1929, 1931, 1933, 1943, 1945, 1957, 1978, 1988, 1990, 1994, 1996, 1997], axis=0)
merged = merged.drop([2020, 2021, 2022, 2024, 2025, 2066, 2079, 2083, 2086], axis=0)
merged = merged.drop([2123, 2156, 2158, 2166, 2168, 2187, 2190, 2197], axis=0)
merged = merged.drop([2203, 2231, 2232, 2244, 2274], axis=0)
merged = merged.drop([2303, 2315, 2321, 2350, 2365, 2374, 2394, 2398], axis=0)
merged = merged.drop([2400, 2429, 2441, 2470, 2494], axis=0)
merged = merged.drop([2501, 2513, 2539, 2565, 2567, 2568, 2570, 2582, 2586], axis=0)
merged = merged.drop([2603, 2608, 2635, 2664, 2669, 2671, 2696, 2697, 2698], axis=0)
merged = merged.drop([2700, 2702, 2731, 2753, 2757, 2761, 2765, 2772, 2771, 2784, 2791], axis=0)
merged = merged.drop([2817, 2824, 2825, 2841, 2843, 2863, 2865], axis=0)
merged = merged.drop([2917, 2915, 2927, 2928, 2929, 2949, 2958, 2962, 2964, 2973, 2975, 2987], axis=0)
merged = merged.drop([3003, 3029, 3031, 3035, 3049, 3060, 3078, 3082, 3096, 3098], axis=0)
merged = merged.drop([3110, 3113, 3117, 3128, 3133, 3137, 3147, 3151, 3153, 3158, 3166, 3167], axis=0)
merged = merged.drop([3206, 3218, 3234, 3249, 3255], axis=0)
merged = merged.drop([3348, 3357, 3359, 3367], axis=0)
merged = merged.drop([3407, 3414, 3426, 3429], axis=0)
merged = merged.drop([3513, 3534, 3539, 3541, 3547, 3549, 3561, 3573], axis=0)
merged = merged.drop([3605, 3607, 3641, 3694, 3695], axis=0)
merged = merged.drop([3706, 3726, 3727, 3732, 3743, 3749, 3752, 3764, 3768, 3771, 3773, 3781, 3782], axis=0)
merged = merged.drop([3852, 3864, 3866, 3880], axis=0)
merged = merged.drop([3903, 3907, 3918, 3986, 3989, 3992, 3997], axis=0)
merged = merged.drop([4014, 4018, 4020, 4022, 4032, 4035, 4036, 4048, 4052, 4079], axis=0)
merged = merged.drop([4113, 4118, 4120, 4138, 4145, 4150, 4152, 4174, 4179, 4181, 4182, 4190], axis=0)
merged = merged.drop([4211, 4231, 4238, 4280, 4282, 4296], axis=0)
merged = merged.drop([4306, 4334, 4335, 4337], axis=0)
merged = merged.drop([4401, 4403, 4404, 4407, 4409, 4414, 4435, 4442, 4447, 4471, 4493], axis=0)
merged = merged.drop([4503, 4568, 4572, 4574, 4577, 4580, 4582], axis=0)
merged = merged.drop([4631, 4641, 4646, 4653, 4669, 4686, 4690], axis=0)
merged = merged.drop([4700, 4702, 4714, 4719, 4736, 4753, 4757], axis=0)
merged = merged.drop([4801, 4848, 4861, 4865, 4866, 4880], axis=0)
merged = merged.drop([4917, 4936, 4979, 4989], axis=0)
merged = merged.drop([5001, 5010, 5041, 5043, 5066], axis=0)
merged = merged.drop([5111, 5152, 5165, 5196, 5198], axis=0)
merged = merged.drop([5200, 5206, 5210, 5220, 5221, 5247, 5280], axis=0)
merged = merged.drop([5301, 5311, 5314, 5324, 5346, 5348, 5356, 5357, 5358, 5361, 5363, 5367, 5397], axis=0)
merged = merged.drop([5406, 5414, 5424, 5425, 5427, 5428, 5429, 5430, 5436, 5451, 5453], axis=0)
merged = merged.drop([5502, 5506, 5512, 5527, 5574], axis=0)
merged = merged.drop([5614, 5674, 5697, 5698], axis=0)
merged = merged.drop([5713, 5728, 5748, 5756, 5766, 5776], axis=0)
merged = merged.drop([5816, 5833, 5837, 5843, 5855, 5869, 5871], axis=0)
merged = merged.drop([5917, 5927, 5978, 5980], axis=0)
merged = merged.drop([6028, 6078, 6079, 6083, 6085], axis=0)
merged = merged.drop([6103, 6186], axis=0)
merged = merged.drop([6218, 6253, 6269, 6290], axis=0)
merged = merged.drop([6326, 6348, 6349, 6352, 6360], axis=0)
merged = merged.drop([6420, 6437, 6452, 6497, 6499], axis=0)
merged = merged.drop([6523, 6535, 6536, 6537, 6561, 6583], axis=0)
merged = merged.drop([6612, 6666], axis=0)
merged = merged.drop([6718, 6732, 6745, 6772, 6789], axis=0)
merged = merged.drop([6809, 6822, 6831, 6854, 6864, 6886, 6887], axis=0)
merged = merged.drop([6903, 6917, 6968, 6971, 6972, 6977], axis=0)
merged = merged.drop([7110, 7130, 7132, 7134, 7176, 7199], axis=0)
merged = merged.drop([7225, 7235, 7278, 7279], axis=0)
merged = merged.drop([7304, 7346, 7350, 7363], axis=0)
merged = merged.drop([7421, 7428, 7452, 7454, 7455, 7459, 7476], axis=0)
merged = merged.drop([7544, 7556], axis=0)
merged = merged.drop([7621, 7689], axis=0)
merged = merged.drop([7700, 7771, 7773, 7795], axis=0)
merged = merged.drop([7852], axis=0)
merged = merged.drop([7940], axis=0)
merged = merged.drop([8013], axis=0)
merged = merged.drop([8125, 8126, 8142, 8174, 8177, 8179, 8183], axis=0)
merged = merged.drop([8230, 8240, 8250, 8272], axis=0)
merged = merged.drop([8309, 8312, 8320, 8377, 8383], axis=0)
merged = merged.drop([8442, 8446], axis=0)
merged = merged.drop([8512], axis=0)

In [17]:
dup = merged[merged['index'].duplicated(keep=False)]
dup.sort_values(by=['index'])[['level', 'number', 'traditional', 'pinyin_x', 'pinyin_y', 'english', 'part of speech']]

Empty DataFrame
Columns: [level, number, traditional, pinyin_x, pinyin_y, english, part of speech]
Index: []

In [18]:
dup1 = merged[merged['traditional'].duplicated(keep=False)]
dup1.sort_values(by=['traditional'])[['level', 'number', 'traditional', 'pinyin_x', 'pinyin_y', 'english', 'part of speech']]

,level,number,traditional,pinyin_x,pinyin_y,english,part of speech
579,2,180,一定,yīdìng,yi1 ding4,surely;certainly;necessarily;fixed;a certain (...,Adv
8065,6,2529,一定,yīdìng,yi1 ding4,surely;certainly;necessarily;fixed;a certain (...,Vs-attr
358,1,157,一樣,yīyàng,yi1 yang4,same;like;equal to;the same as;just like,Vs
2511,4,1274,一樣,yīyàng,yi1 yang4,same;like;equal to;the same as;just like,N
223,1,39,一點,yīdiǎn(r),yi1 dian3,a bit; a little bit;(used in negative expressi...,Det
...,...,...,...,...,...,...,...
1399,4,255,點,diăn,dian3,point;dot;drop;speck;o'clock;point (in space o...,M
54,1,51,點,diǎn,dian3,point;dot;drop;speck;o'clock;point (in space o...,M
1400,4,256,點,diăn,dian3,point;dot;drop;speck;o'clock;point (in space o...,N
3453,5,652,鼓勵,gŭlì,gu3 li4,to encourage,N
3454,5,653,鼓勵,gŭlì,gu3 li4,to encourage,V

In [19]:
merged.to_csv('./data/tocfl_cleaned.csv', index=True)

In [20]:
# mapping_5 = {
#     'a': 'a5', 'i': 'i5', 'u': 'u5', 'ü': 'v5', 'e': 'e5', 'o': 'o5',
#     'ao': 'ao5', 'ou': 'ou5', 'ai': 'ai5', 'ei': 'ei5', 'ui': 'ui5', 'ia': 'ia5',
#     'ie': 'ie5', 'an': 'an5', 'en': 'en5', 'in': 'in5', 'un': 'un5', 'er': 'er5',
#     'iao': 'iao5', 'iou': 'iou5', 'iai': 'iai5', 'ian': 'ian5', 'ien': 'ien5', 'ang': 'ang5',
#     'eng': 'eng5', 'ing': 'ing5', 'ong': 'ong5', 'iang': 'iang5', 'uāng': 'uang5', 'uēng': 'ueng5',
# }
# mapping = {
#     'iāng': 'iang1', 'iáng': 'iang2', 'iǎng': 'iang3', 'iàng': 'iang4',
#     'ūang': 'uang1', 'úang': 'uang2', 'ǔang': 'uang3', 'ùang': 'uang4',
#     'ūeng': 'ueng1', 'úeng': 'ueng2', 'ǔeng': 'ueng3', 'ùeng': 'ueng4',
# 
#     'āng': 'ang1', 'áng': 'ang2', 'ǎng': 'ang3', 'àng': 'ang4',
#     'ēng': 'eng1', 'éng': 'eng2', 'ěng': 'eng3', 'èng': 'eng4',
#     'īng': 'ing1', 'íng': 'ing2', 'ǐng': 'ing3', 'ìng': 'ing4',
#     'ōng': 'ong1', 'óng': 'ong2', 'ǒng': 'ong3', 'òng': 'ong4',
#     'iān': 'ian1', 'ián': 'ian2', 'iǎn': 'ian3', 'iàn': 'ian4',
#     'iēn': 'ien1', 'ién': 'ien2', 'iěn': 'ien3', 'ièn': 'ien4',
#     'iāo': 'iao1', 'iáo': 'iao2', 'iǎo': 'iao3', 'iào': 'iao4',
#     'iōu': 'iou1', 'ióu': 'iou2', 'iǒu': 'iou3', 'iòu': 'iou4',
#     'iāi': 'iai1', 'iái': 'iai2', 'iǎi': 'iai3', 'iài': 'iai4',
# 
#     'ān': 'an1', 'án': 'an2', 'ǎn': 'an3', 'àn': 'an4',
#     'ēn': 'en1', 'én': 'en2', 'ěn': 'en3', 'èn': 'en4',
#     'īn': 'in1', 'ín': 'in2', 'ǐn': 'in3', 'ìn': 'in4',
#     'ūn': 'un1', 'ún': 'un2', 'ǔn': 'un3', 'ùn': 'un4',
#     'ēr': 'er1', 'ér': 'er2', 'ěr': 'er3', 'èr': 'er4',
#     'āo': 'ao1', 'áo': 'ao2', 'ǎo': 'ao3', 'ào': 'ao4',
#     'ōu': 'ou1', 'óu': 'ou2', 'ǒu': 'ou3', 'òu': 'ou4',
# 
#     'āi': 'ai1','ái': 'ai2','ǎi': 'ai3','ài': 'ai4',
#     'ēi': 'ei1','éi': 'ei2','ěi': 'ei3','èi': 'ei4',
#     'ūi': 'ui1','uí': 'ui2','ǔi': 'ui3','ùi': 'ui4',
#     'iā': 'ia1','iá': 'ia2','iǎ': 'ia3','ià': 'ia4',
#     'iē': 'ie1','ié': 'ie2','iě': 'ie3','iè': 'ie4',
# 
#     'ā': 'a1','á': 'a2','ǎ': 'a3','à': 'a4',
#     'ī': 'i1','í': 'i2','ǐ': 'i3','ì': 'i4',
#     'ū': 'u1','ú': 'u2','ǔ': 'u3','ù': 'u4',
#     'ǖ': 'v1','ǘ': 'v2','ǚ': 'v3','ǜ': 'v4',
#     'ē': 'e1','é': 'e2','ě': 'e3','è': 'e4',
#     'ō': 'o1','ó': 'o2','ǒ': 'o3','ò': 'o4',
# }
# 
# import re
# 
# mismatches = []
# for i, row in merged.iterrows():
#     x = row['pinyin_x'].lower().replace(r'\(.*\)', '')
#     x = re.sub(r'\(.*?\)', '', x)
#     x = re.sub(r'\/.*', '', x)
#     y = row['pinyin_y'].lower()
# 
#     for k, v in mapping.items():
#         x = re.sub(rf'{k}(?=b|p|m|f|d|t|n|l|g|k|h|j|q|x|s|r|z|c|w|y|\s|$)', v, x)
#         y = re.sub(rf'{k}(?=\s|$)', v, y)
# 
#     for k, v in mapping_5.items():
#         x = re.sub(rf'{k}(?=\s|$)', v, x)
#         y = re.sub(rf'{k}(?=\s|$)', v, y)
# 
#     if x.replace(' ', '') != y.replace(' ', ''):
#         # print(i, row['traditional'], row['pinyin_x'], x.replace(' ', ''), y.replace(' ', ''))
#         mismatches.append(i)
#         
# merged['mismatch'] = merged.index.isin(mismatches)